from typing import Dict, List, NamedTuple


class RF4RegionData(NamedTuple):
    connecting_regions: List[str] = []

region_data_table: Dict[str, RF4RegionData] = {
    "Menu": RF4RegionData(["Selphia"]),
    "Selphia": RF4RegionData([
        "Yokmir Forest",
        "Selphia Plains",
        "Selphia: Dragon Lake",
        "Floating Empire",
        "Sharance Maze",

        "Forge",
        "Chemistry",
        "Crafting",
        "Cooking",
        "EZ Cooking",
        "Pro Cooking",

        "Selphia Clothing Shop",
        #"Jewelry Shop",
        "Mineral",
        "Make Lumber",
        "Build a Monster Barn!"
        ]),
    "Selphia: Dragon Lake": RF4RegionData(["Obsidian Mansion"]),
    "Yokmir Forest": RF4RegionData(["Yokmir Cave", "Yokmir Forest (Boss)"]),
    "Yokmir Forest (Boss)": RF4RegionData(["Yokmir Forest (Second Boss)"]),
    "Yokmir Forest (Second Boss)": RF4RegionData(),

    "Yokmir Cave": RF4RegionData(["Yokmir Cave F1"]),
    "Yokmir Cave F1": RF4RegionData(["Yokmir Cave F2"]),
    "Yokmir Cave F2": RF4RegionData(["Yokmir Cave F3"]),
    "Yokmir Cave F3": RF4RegionData(),
    "Obsidian Mansion": RF4RegionData(["Selphia", "Selphia Plains - West", "Obsidian Mansion (Boss)"]),
    "Obsidian Mansion (Boss)": RF4RegionData(),

    "Selphia Plains": RF4RegionData([
        "Summer Field",
        "Keeno Lake",
        "Cluck Cluck Nest",
        "Water Ruins",
        "Selphia Plains - West",
        "Selphia Plains - East",
        "Anywhere (Rare)",
        "Mineral",
    ]),
    "Mineral": RF4RegionData(),
    "Anywhere (Rare)": RF4RegionData(),
    "Summer Field": RF4RegionData(["Summer Field"]),
    "Keeno Lake": RF4RegionData(),
    "Cluck Cluck Nest": RF4RegionData(["Selphia Plains"]),
    "Water Ruins": RF4RegionData(["Water Ruins (Boss)","Water Ruins (Second Boss)"]),
    "Water Ruins (Boss)": RF4RegionData(),
    "Water Ruins (Second Boss)": RF4RegionData(),

    "Selphia Plains - West": RF4RegionData([
        "Obsidian Mansion",
        "Leon Karnak",
        "Autumn Road",
    ]),
    "Leon Karnak": RF4RegionData(["Rune Prana","Leon Karnak (Boss)"]),
    "Leon Karnak (Boss)": RF4RegionData(),
    

    "Autumn Road": RF4RegionData([
        "Delirium Lava Ruins",
        "Revival Cave",
        "Autumn Spring",
        "Silver Lake",
        "Autumn River",
        "Autumn Field",
        "Maya Road"
    ]),
    "Delirium Lava Ruins": RF4RegionData(["Delirium Lava Ruins F1"]),
    "Delirium Lava Ruins F1": RF4RegionData(["Delirium Lava Ruins F2"]),
    "Delirium Lava Ruins F2": RF4RegionData(["Delirium Lava Ruins (Boss)"]),
    "Delirium Lava Ruins (Boss)": RF4RegionData(),

    "Revival Cave": RF4RegionData(["Revival Cave (Boss)"]),
    "Revival Cave (Boss)": RF4RegionData(),

    "Autumn Spring": RF4RegionData(),
    "Autumn River": RF4RegionData(),
    "Autumn Field": RF4RegionData(["Autumn Road"]),
    
    "Silver Lake": RF4RegionData(["Winter Field","Winter Spring"]),
    "Winter Field": RF4RegionData(["Autumn Road"]),
    "Winter Spring": RF4RegionData(),

    "Maya Road": RF4RegionData(["Maya Road F1"]),
    "Maya Road F1": RF4RegionData(["Maya Underground (1)","Maya Road (Underground)"]),
    "Maya Road (Underground)": RF4RegionData(),
    "Maya Underground (1)": RF4RegionData(["Maya Underground (2)"]),
    "Maya Underground (2)": RF4RegionData(["Maya Road F2"]),
    "Maya Road F2": RF4RegionData(["Maya Road (Boss)"]),
    "Maya Road (Boss)": RF4RegionData(["Sechs Territory"]),
    
    "Sechs Territory": RF4RegionData(["Sechs Territory F1"]),
    "Sechs Territory F1": RF4RegionData(["Sechs Territory (Cave)","Sechs Cave","Sechs Territory F2"]),
    "Sechs Territory (Cave)": RF4RegionData(),
    "Sechs Cave": RF4RegionData(),
    "Sechs Territory F2": RF4RegionData(["Sechs Territory (Boss)"]),
    "Sechs Territory (Boss)": RF4RegionData(["Prepare for Marriage!"]),

    "Selphia Plains - East": RF4RegionData([
        "Summer Spring",
        "Sercerezo Hill",
    ]),
    "Summer Spring": RF4RegionData(),

    "Sercerezo Hill": RF4RegionData([
        "Spring Field",
        "Idra Cave",
        "Sand Pond",
        "Sercerezo Lake",
        "Demon's Den",
        "Spring Spring",
    ]),
    "Spring Field": RF4RegionData(["Sercerezo Hill"]),
    "Spring Spring": RF4RegionData(),
    "Idra Cave": RF4RegionData(["Idra Cave B1"]),
    "Idra Cave B1": RF4RegionData(["Idra Cave B2"]),
    "Idra Cave B2": RF4RegionData(["Idra Cave (Boss)"]),
    "Idra Cave (Boss)": RF4RegionData(),
    "Sand Pond": RF4RegionData(),
    "Sercerezo Lake": RF4RegionData(),
    "Demon's Den": RF4RegionData(["Sercerezo Hill","Field Dungeon","Demon's Den (Boss)"]),
    "Demon's Den (Boss)": RF4RegionData(["Sercerezo Hill","Field Dungeon"]),
    "Field Dungeon": RF4RegionData(),

    "Forge": RF4RegionData(["Forge Bronze"]),
    "Forge Bronze": RF4RegionData(["Forge Silver"]),
    "Forge Silver": RF4RegionData(["Forge Gold"]),
    "Forge Gold": RF4RegionData(["Forge Platinum"]),
    "Forge Platinum": RF4RegionData(["Forge Orichalcum"]),
    "Forge Orichalcum": RF4RegionData(["Forge Dragonic"]),
    "Forge Dragonic": RF4RegionData(),

    "Crafting": RF4RegionData(["Crafting Bronze"]),
    "Crafting Bronze": RF4RegionData(["Crafting Silver"]),
    "Crafting Silver": RF4RegionData(["Crafting Gold"]),
    "Crafting Gold": RF4RegionData(["Crafting Platinum"]),
    "Crafting Platinum": RF4RegionData(["Crafting Orichalcum"]),
    "Crafting Orichalcum": RF4RegionData(["Crafting Dragonic"]),
    "Crafting Dragonic": RF4RegionData(),

    "Chemistry": RF4RegionData(),

    "Cooking": RF4RegionData(),
    "EZ Cooking": RF4RegionData(),
    "Pro Cooking": RF4RegionData(),

    "Mineral": RF4RegionData(),

    "Selphia Clothing Shop": RF4RegionData(),
    #"Jewelry Shop": RF4RegionData(),

    "Floating Empire": RF4RegionData(["Floating Empire - East", "Floating Empire - West", "Floating Empire - South"]),
    "Floating Empire - West": RF4RegionData(["Floating Empire - West (Boss)"]),
    "Floating Empire - West (Boss)": RF4RegionData(),
    "Floating Empire - East": RF4RegionData(["Floating Empire - East (Boss)"]),
    "Floating Empire - East (Boss)": RF4RegionData(),
    "Floating Empire - South": RF4RegionData(["Floating Empire - South (Boss)"]),
    "Floating Empire - South (Boss)": RF4RegionData(),

    "Sharance Maze": RF4RegionData(["Sharance Maze (Boss)"]),
    "Sharance Maze (Boss)": RF4RegionData(["Sharance Maze: Deepwater Shrine Lv 10 (Boss)"]),
    "Sharance Maze: Deepwater Shrine Lv 10 (Boss)": RF4RegionData(["Sharance Maze: Dragon Ruins Level 12 (Boss)"]),
    "Sharance Maze: Dragon Ruins Level 12 (Boss)": RF4RegionData(),

    "Rune Prana": RF4RegionData(["Rune Prana F1"]),
    "Rune Prana F1": RF4RegionData(["Rune Prana F1 (Boss)"]),
    "Rune Prana F1 (Boss)": RF4RegionData(["Rune Prana F2"]),
    "Rune Prana F2": RF4RegionData(["Rune Prana F2 (Boss)"]),
    "Rune Prana F2 (Boss)": RF4RegionData(["Rune Prana F3"]),
    "Rune Prana F3": RF4RegionData(["Rune Prana F3 (Boss)"]),
    "Rune Prana F3 (Boss)": RF4RegionData(["Rune Prana F4"]),
    "Rune Prana F4": RF4RegionData(["Rune Prana F4 (Boss)"]),
    "Rune Prana F4 (Boss)": RF4RegionData(["Rune Prana F5"]),
    "Rune Prana F5": RF4RegionData(["Rune Prana F5 (Boss)"]),
    "Rune Prana F5 (Boss)": RF4RegionData(["Rune Prana F6"]),
    "Rune Prana F6": RF4RegionData(["Rune Prana F6 (Boss)"]),
    "Rune Prana F6 (Boss)": RF4RegionData(["Rune Prana F7"]),
    "Rune Prana F7":  RF4RegionData(["Rune Prana F7 (Boss)"]),
    "Rune Prana F7 (Boss)":  RF4RegionData(),


    # Requests
    "Make Lumber": RF4RegionData(["Make a shipment!"]),
    "Give an item!": RF4RegionData(["Purchase Rice!"]),
    "Purchase Rice!": RF4RegionData(["Make Material Stone!"]),
    "Make Material Stone!": RF4RegionData(["Try Fishing!", "Harvest Toyherb!"]),
    "Try Fishing!": RF4RegionData(["Use a Fertilizer Bin!","Harvest Potato!"]),
    "Use a Fertilizer Bin!": RF4RegionData(["Mine Iron!"]),
    "Mine Iron!": RF4RegionData(["Raise friendship levels! (1)"]),
    "Raise friendship levels! (1)": RF4RegionData(["Look at illustrations!","Check difficulty level!","Get an Airship License!"]),
    "Look at illustrations!": RF4RegionData([]),
    "Check difficulty level!": RF4RegionData([]),
    "Get an Airship License!": RF4RegionData(["Get a Cooking Table!"]),
    "Get a Cooking Table!": RF4RegionData(["Start Cooking!"]),
    "Start Cooking!": RF4RegionData(["Get a Forge!"]),
    "Get a Forge!": RF4RegionData(["Forge a weapon!"]),
    "Forge a weapon!": RF4RegionData(["Make a farming tool!"]),
    "Make a farming tool!": RF4RegionData(["Get a Crafting Table!"]),
    "Get a Crafting Table!": RF4RegionData(["Make some armor!"]),
    "Make some armor!": RF4RegionData(["Get a Chemistry Set!"]),
    "Get a Chemistry Set!": RF4RegionData(["Make some medicine!"]),
    "Make some medicine!": RF4RegionData(["Raise a skill level!"]),
    "Raise a skill level!": RF4RegionData(["Raise a weapon skill level!"]),
    "Raise a weapon skill level!": RF4RegionData(["Upgrade a weapon!"]),
    "Upgrade a weapon!": RF4RegionData(["Raise a magic skill level!"]),
    "Raise a magic skill level!": RF4RegionData(["Upgrade your armor!"]),
    "Upgrade your armor!": RF4RegionData(["Use a nutrient!"]),
    "Use a nutrient!": RF4RegionData(["Raise shipment rates!"]),
    "Raise shipment rates!": RF4RegionData(["Get a Shop License!"]),
    "Get a Shop License!": RF4RegionData(["Prepare for a typhoon!"]),
    "Prepare for a typhoon!": RF4RegionData(["Befriend 5 monsters!"]),
    "Befriend 5 monsters!": RF4RegionData(["Upgrade a Staff!"]),
    "Upgrade a Staff!": RF4RegionData(["Raise friendship levels! (5)"]),
    "Raise friendship levels! (5)": RF4RegionData([]),
    "Ship a level 10 flower!": RF4RegionData([]),
    "Raise total shipment fee!": RF4RegionData(["Give a Turnip Heaven!"]),
    "Harvest a large gold crop!": RF4RegionData(["Ship a gold level 10 crop!"]),
    "Harvest all crops!": RF4RegionData(["Raise a skill level to 50!","Befriend 50 monsters!","Raise friendship levels! (10)"]),
    "Ship a gold level 10 crop!": RF4RegionData([]),
    "Raise a skill level to 50!": RF4RegionData([]),
    "Befriend 50 monsters!": RF4RegionData(["Raise a skill level to 80!", "Complete the Sharance Maze!"]),
    "Raise friendship levels! (10)": RF4RegionData([]),
    "Get a 50% shipment rate!": RF4RegionData([]),
    "Raise a skill level to 80!": RF4RegionData([]),
    "Complete the Sharance Maze!": RF4RegionData(["From Eliza!"]),
    "Give Dolce a Moondrop!": RF4RegionData([]),
    "Build a Monster Barn!": RF4RegionData(["Befriend monsters!"]),
    "Befriend monsters!": RF4RegionData(["Befriend an item monster!", "Give a monster a task!","Ride on a monster friend!"]),
    "Ride on a monster friend!": RF4RegionData([]),
    "Befriend an item monster!": RF4RegionData([]),
    "Give a monster a task!": RF4RegionData([]),
    "Befriend a boss monster!": RF4RegionData([]),
    "Prepare for Marriage!": RF4RegionData([]),
    "From Eliza!": RF4RegionData([]),
    "Make a shipment!": RF4RegionData(["Give an item!"]),
    "Harvest Potato!": RF4RegionData(["Harvest 20 Turnip!", "Harvest 5 Radishes!", "Ship a level 2 Turnip!"]),
    "Harvest 20 Turnip!": RF4RegionData([]),
    "Harvest 5 Radishes!": RF4RegionData(["Harvest 6 veggies!","Ship a level 5 veggie!"]),
    "Ship a level 2 Turnip!": RF4RegionData([]),
    "Harvest 6 veggies!": RF4RegionData(["Till Corn", "Harvest a Sword Flower!", "Harvest a Shield Flower!", "Complete a field dungeon!"]),
    "Ship a level 5 veggie!": RF4RegionData(["Give Dylas a Carrot!","Harvest 12 veggies!"]),
    "Till Corn": RF4RegionData([]),
    "Give Dylas a Carrot!": RF4RegionData([]),
    "Harvest 12 veggies!": RF4RegionData(["Befriend a boss monster!","Ship a level 10 veggie!","Harvest certain veggies!","Cut down a Shining Tree!","Harvest 20 Oranges!"]),
    "Ship a level 10 veggie!": RF4RegionData([]),
    "Harvest certain veggies!": RF4RegionData(["Harvest a large veggie!"]),
    "Cut down a Shining Tree!": RF4RegionData(["Harvest 50 Grapes!","Harvest 50 Apples!"]),
    "Harvest 20 Oranges!": RF4RegionData([]),
    "Harvest a large veggie!": RF4RegionData(["Harvest non-golden veggies!"]),
    "Harvest 50 Grapes!": RF4RegionData([]),
    "Harvest 50 Apples!": RF4RegionData([]),
    "Harvest non-golden veggies!": RF4RegionData(["Gift for Margaret!"]),
    "Gift for Margaret!": RF4RegionData(["Raise total shipment fee!","Get a 25% shipment rate!"]),
    "Get a 25% shipment rate!": RF4RegionData(["Get a 50% shipment rate!"]),
    "Give a Turnip Heaven!": RF4RegionData(["Harvest a large gold crop!", "Harvest all crops!"]),
    "Harvest a Sword Flower!": RF4RegionData([]),
    "Harvest a Shield Flower!": RF4RegionData([]),
    "Complete a field dungeon!": RF4RegionData([]),
    "Harvest Toyherb!": RF4RegionData(["Harvest 3 flowers!"]),
    "Harvest 3 flowers!": RF4RegionData(["Give Amber a Toyherb!","Harvest 9 Charm Blues!"]),
    "Give Amber a Toyherb!": RF4RegionData(["Give Dolce a Moondrop!"]),
    "Harvest 9 Charm Blues!": RF4RegionData(["Harvest Cherry Grass!","Harvest 5 flowers!"]),
    "Harvest Cherry Grass!": RF4RegionData([]),
    "Harvest 5 flowers!": RF4RegionData(["Till a 4-Leaf Clover!"]),
    "Till a 4-Leaf Clover!": RF4RegionData(["Fight using an Ironleaf!"]),
    "Fight using an Ironleaf!": RF4RegionData(["Harvest a large flower!","Harvest Autumn Grass!"]),
    "Harvest a large flower!": RF4RegionData(["Harvest Blue Crystal!"]),
    "Harvest Autumn Grass!": RF4RegionData(["Ship a level 10 flower!"]),
    "Harvest Blue Crystal!": RF4RegionData(["Harvest Green Crystal!"]),
    "Harvest Green Crystal!": RF4RegionData(["Harvest Red Crystal!"]),
    "Harvest Red Crystal!": RF4RegionData(["Harvest White Crystal!"]),
    "Harvest White Crystal!": RF4RegionData(["Harvest almost all crops!"]),
    "Harvest almost all crops!": RF4RegionData([]),
}   

def get_exit(region, exit_name):
    for exit in region.exits:
        if exit.connected_region.name == exit_name:
            return exit