import logging

slot_data_defaults = {
    "DeathLink": False,
    "ShopboxLink": False,
    "Goal": 1,
    "GoalLoc": "",
    "Shipping_Percent": 50,
    "ChestSanity": True,
    "Friendsanity": False,
    "Tamesanity": False,
    "OutfitSanity": False,
    "ShipSanities": {
        "CropSanity": False,
        "GoldcropSanity": False,
        "LargeCropSanity": False,
        "DropSanity": False,
        "SpellSanity": False,
        "MineralSanity": False,
        "GrocerySanity": False,
        "ForageSanity": False,
        "Fishsanity": False,
        "ForgeSanity": False,
        "CraftSanity": False,
        "DishSanity": False,
        "ChemicSanity": False,
    },
    "RequestSanity": False,
    "BoxSanity": False,
    "BarrierSanity": False,
    "SearchSanity": False,
    "fortress_runespheres": 6,
    "runeprana_runespheres": 6,
    "sphere_hunt_spheres": 6,
    "no_jones_fee": False,
    "exp_multiplier": 2,
    "skill_exp_multiplier": 2,
    "friendship_multiplier": 1,
    "drop_rate_increase": 20,
    "open_airship": False,
    "gay_dating": False,
    "start_weapon": 0x149,
    "progressive_weapon": False,
    "progressive_armor": False,
    "progressive_accessory": False,
    "character_appearance": 0,
}